language: node_js
node_js:
  - "0.10"

env:
  global:
    - secure: "Ju77ouEvmRzOi68q6Qws6OMaVdGlVO6QJt/1Z3UoJbEbnaBQmkaY0LRK9xyl6i8HK67pNErxMtosE+jrZU8Jd0RfHHQxSyVhLGVRnWvX9KS+DVV/s+4buZGAp1IoZDkzE88M0jLVsYuWTADe6XWPnI+V9YAoLptQ/e4vdZR7aQc="


# ~*** ------------------------------------------------->
#
# IMPORTANT NOTE:
#
# Please don't change this file manually!
# It is automatically compiled from `.travis.yml.tpl`
# in order to encrypt sensitive information using the
# repo public key.
#
# Change `.travis.yml.tpl` instead.
#
# <--------------------------------------------------- ***~


